# This workflow runs functional tests, but only when a PR is added to the merge queue.
# It also can be run manually.

name: Functional tests

on:
  merge_group:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  functional_tests:
    name: Functional tests
    runs-on: self-hosted

    steps:
      - name: Check out
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: |
          uv sync --group tests
          uv run playwright install

      - name: Run tests
        run: |
          uv run pytest -x --retries 3
        env:
          KAMIHI_TESTING__BOT_TOKEN: ${{ secrets.TOKEN }}
          KAMIHI_TESTING__BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
          KAMIHI_TESTING__USER_ID: ${{ secrets.USER_ID }}
          KAMIHI_TESTING__TG_PHONE_NUMBER: ${{ secrets.TG_PHONE_NUMBER }}
          KAMIHI_TESTING__TG_API_ID: ${{ secrets.TG_API_ID }}
          KAMIHI_TESTING__TG_API_HASH: ${{ secrets.TG_API_HASH }}
          KAMIHI_TESTING__TG_SESSION: ${{ secrets.TG_SESSION }}
          KAMIHI_TESTING__TG_DC_ID: ${{ secrets.TG_DC_ID }}
          KAMIHI_TESTING__TG_DC_IP: ${{ secrets.TG_DC_IP }}
