name: Release

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'bump')"
    outputs:
      REVISION: ${{ env.REVISION }}

    steps:
      - name: Check out
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          token: "${{ secrets.PAT }}"
          fetch-depth: 0

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@bb4f1df6601e2a1a891506581b0c53acdc88e07d # 0.26.0
        with:
          github_token: ${{ secrets.PAT }}
          changelog_increment_filename: body.md

      - name: Upload incremental changelog
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: changelog
          path: body.md

  build:
    name: Build project
    runs-on: ubuntu-latest
    needs: bump-version
    if: "!startsWith(github.event.head_commit.message, 'docs') && !startsWith(github.event.head_commit.message, 'chore:') && !startsWith(github.event.head_commit.message, 'test') && !startsWith(github.event.head_commit.message, 'Revert')"

    steps:
      - name: Check out
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          ref: ${{ github.ref }}
          token: "${{ secrets.PAT }}"
          fetch-depth: 0

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Build project
        run: |
          uv sync --dev
          uv build
          
      - name: Store the distribution packages
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: python-package-distributions
          path: dist/

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/kamihi
    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - bump-version
      - build

    steps:
      - name: Check out
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          ref: ${{ github.ref }}

      - name: Download changelog
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          name: changelog

      - name: Download all the dists
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          name: python-package-distributions
          path: dist/

      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          body_path: body.md
          tag_name: ${{ needs.bump-version.outputs.REVISION }}
          files: |
            dist/kamihi-${{ needs.bump-version.outputs.REVISION }}-py3-none-any.whl

  docs:
    name: Deploy documentation
    runs-on: ubuntu-latest
    needs: bump-version

    steps:
      - name: Check out
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          ref: ${{ github.ref }}
          token: "${{ secrets.PAT }}"
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7

      - name: Install dependencies
        run: uv sync --group docs

      - name: Build site and deploy
        run: uv run mike deploy --push --update-aliases ${{ needs.bump-version.outputs.REVISION }} latest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Set latest
        run: uv run mike set-default --push latest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
